### ISSUE TITLE
Run error!

### ISSUE THREAD

**Issue by QDqiaodong** [jaredlam/BubbleView#1]
when i found in git, i was surprised that your code is my need!
but,when i run it in my phone. the result is not like your!
the bubbleView not  Collision deformation why?
i think i need your help ,thank you very much!

**Comment by jaredlam** [comment]
Sorry for late response, Please give me some more details of error so I can help you.

**Comment by QDqiaodong** [comment]
ok ,Thank you very much. I was very superised ! Problem has been resolved. I was programming a project ,and the result seem expectation.
